(cl:defpackage behavior_manager-msg
  (:use )
  (:export
   "<DEPTHBEHAVIORACTION>"
   "DEPTHBEHAVIORACTION"
   "<DEPTHBEHAVIORACTIONFEEDBACK>"
   "DEPTHBEHAVIORACTIONFEEDBACK"
   "<DEPTHBEHAVIORACTIONGOAL>"
   "DEPTHBEHAVIORACTIONGOAL"
   "<DEPTHBEHAVIORACTIONRESULT>"
   "DEPTHBEHAVIORACTIONRESULT"
   "<DEPTHBEHAVIORFEEDBACK>"
   "DEPTHBEHAVIORFEEDBACK"
   "<DEPTHBEHAVIORGOAL>"
   "DEPTHBEHAVIORGOAL"
   "<DEPTHBEHAVIORRESULT>"
   "DEPTHBEHAVIORRESULT"
  ))

