; Auto-generated. Do not edit!


(cl:in-package behavior_manager-msg)


;//! \htmlinclude DepthBehaviorGoal.msg.html

(cl:defclass <DepthBehaviorGoal> (roslisp-msg-protocol:ros-message)
  ((target_depth
    :reader target_depth
    :initarg :target_depth
    :type cl:float
    :initform 0.0)
   (publish_mismatch
    :reader publish_mismatch
    :initarg :publish_mismatch
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass DepthBehaviorGoal (<DepthBehaviorGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DepthBehaviorGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DepthBehaviorGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name behavior_manager-msg:<DepthBehaviorGoal> is deprecated: use behavior_manager-msg:DepthBehaviorGoal instead.")))

(cl:ensure-generic-function 'target_depth-val :lambda-list '(m))
(cl:defmethod target_depth-val ((m <DepthBehaviorGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader behavior_manager-msg:target_depth-val is deprecated.  Use behavior_manager-msg:target_depth instead.")
  (target_depth m))

(cl:ensure-generic-function 'publish_mismatch-val :lambda-list '(m))
(cl:defmethod publish_mismatch-val ((m <DepthBehaviorGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader behavior_manager-msg:publish_mismatch-val is deprecated.  Use behavior_manager-msg:publish_mismatch instead.")
  (publish_mismatch m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DepthBehaviorGoal>) ostream)
  "Serializes a message object of type '<DepthBehaviorGoal>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'target_depth))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'publish_mismatch) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DepthBehaviorGoal>) istream)
  "Deserializes a message object of type '<DepthBehaviorGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'target_depth) (roslisp-utils:decode-double-float-bits bits)))
    (cl:setf (cl:slot-value msg 'publish_mismatch) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DepthBehaviorGoal>)))
  "Returns string type for a message object of type '<DepthBehaviorGoal>"
  "behavior_manager/DepthBehaviorGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DepthBehaviorGoal)))
  "Returns string type for a message object of type 'DepthBehaviorGoal"
  "behavior_manager/DepthBehaviorGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DepthBehaviorGoal>)))
  "Returns md5sum for a message object of type '<DepthBehaviorGoal>"
  "0300ee0e4c47883af7d20c2eef863db7")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DepthBehaviorGoal)))
  "Returns md5sum for a message object of type 'DepthBehaviorGoal"
  "0300ee0e4c47883af7d20c2eef863db7")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DepthBehaviorGoal>)))
  "Returns full string definition for message of type '<DepthBehaviorGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# ======= Goal =======~%float64 target_depth     # 目标深度（米）~%bool    publish_mismatch # 是否发布深度误差~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DepthBehaviorGoal)))
  "Returns full string definition for message of type 'DepthBehaviorGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# ======= Goal =======~%float64 target_depth     # 目标深度（米）~%bool    publish_mismatch # 是否发布深度误差~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DepthBehaviorGoal>))
  (cl:+ 0
     8
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DepthBehaviorGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'DepthBehaviorGoal
    (cl:cons ':target_depth (target_depth msg))
    (cl:cons ':publish_mismatch (publish_mismatch msg))
))
