<?xml version="1.0"?>
<package format="2">
  <name>ros_behavior_tree</name>
  <version>0.1.0</version>
  <description>Behavior tree node that consumes ROS and NAV (MOOS-style) navigation topics.</description>
  <maintainer email="dev@example.com">ros_behavior_tree maintainer</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>behaviortree_cpp_v3</build_depend>
  <build_depend>common_msgs</build_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>roslib</build_depend>
  <build_depend>std_msgs</build_depend>

  <exec_depend>behaviortree_cpp_v3</exec_depend>
  <exec_depend>common_msgs</exec_depend>
  <exec_depend>roscpp</exec_depend>
  <exec_depend>roslib</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
  </export>
</package>
