// Generated by gencpp from file behavior_manager/DepthBehaviorGoal.msg
// DO NOT EDIT!


#ifndef BEHAVIOR_MANAGER_MESSAGE_DEPTHBEHAVIORGOAL_H
#define BEHAVIOR_MANAGER_MESSAGE_DEPTHBEHAVIORGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behavior_manager
{
template <class ContainerAllocator>
struct DepthBehaviorGoal_
{
  typedef DepthBehaviorGoal_<ContainerAllocator> Type;

  DepthBehaviorGoal_()
    : target_depth(0.0)
    , publish_mismatch(false)  {
    }
  DepthBehaviorGoal_(const ContainerAllocator& _alloc)
    : target_depth(0.0)
    , publish_mismatch(false)  {
  (void)_alloc;
    }



   typedef double _target_depth_type;
  _target_depth_type target_depth;

   typedef uint8_t _publish_mismatch_type;
  _publish_mismatch_type publish_mismatch;





  typedef boost::shared_ptr< ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator> const> ConstPtr;

}; // struct DepthBehaviorGoal_

typedef ::behavior_manager::DepthBehaviorGoal_<std::allocator<void> > DepthBehaviorGoal;

typedef boost::shared_ptr< ::behavior_manager::DepthBehaviorGoal > DepthBehaviorGoalPtr;
typedef boost::shared_ptr< ::behavior_manager::DepthBehaviorGoal const> DepthBehaviorGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator1> & lhs, const ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator2> & rhs)
{
  return lhs.target_depth == rhs.target_depth &&
    lhs.publish_mismatch == rhs.publish_mismatch;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator1> & lhs, const ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behavior_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0300ee0e4c47883af7d20c2eef863db7";
  }

  static const char* value(const ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0300ee0e4c47883aULL;
  static const uint64_t static_value2 = 0xf7d20c2eef863db7ULL;
};

template<class ContainerAllocator>
struct DataType< ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behavior_manager/DepthBehaviorGoal";
  }

  static const char* value(const ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# ======= Goal =======\n"
"float64 target_depth     # 目标深度（米）\n"
"bool    publish_mismatch # 是否发布深度误差\n"
;
  }

  static const char* value(const ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_depth);
      stream.next(m.publish_mismatch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DepthBehaviorGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behavior_manager::DepthBehaviorGoal_<ContainerAllocator>& v)
  {
    s << indent << "target_depth: ";
    Printer<double>::stream(s, indent + "  ", v.target_depth);
    s << indent << "publish_mismatch: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.publish_mismatch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOR_MANAGER_MESSAGE_DEPTHBEHAVIORGOAL_H
