// Generated by gencpp from file behavior_manager/DepthBehaviorFeedback.msg
// DO NOT EDIT!


#ifndef BEHAVIOR_MANAGER_MESSAGE_DEPTHBEHAVIORFEEDBACK_H
#define BEHAVIOR_MANAGER_MESSAGE_DEPTHBEHAVIORFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behavior_manager
{
template <class ContainerAllocator>
struct DepthBehaviorFeedback_
{
  typedef DepthBehaviorFeedback_<ContainerAllocator> Type;

  DepthBehaviorFeedback_()
    : success(false)
    , message()  {
    }
  DepthBehaviorFeedback_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct DepthBehaviorFeedback_

typedef ::behavior_manager::DepthBehaviorFeedback_<std::allocator<void> > DepthBehaviorFeedback;

typedef boost::shared_ptr< ::behavior_manager::DepthBehaviorFeedback > DepthBehaviorFeedbackPtr;
typedef boost::shared_ptr< ::behavior_manager::DepthBehaviorFeedback const> DepthBehaviorFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator1> & lhs, const ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator1> & lhs, const ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behavior_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behavior_manager/DepthBehaviorFeedback";
  }

  static const char* value(const ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# ======= Result =======\n"
"bool    success          # 行为是否成功执行\n"
"string  message          # 成功或失败的说明\n"
"\n"
;
  }

  static const char* value(const ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DepthBehaviorFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behavior_manager::DepthBehaviorFeedback_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOR_MANAGER_MESSAGE_DEPTHBEHAVIORFEEDBACK_H
