// Generated by gencpp from file behavior_manager/DepthBehaviorResult.msg
// DO NOT EDIT!


#ifndef BEHAVIOR_MANAGER_MESSAGE_DEPTHBEHAVIORRESULT_H
#define BEHAVIOR_MANAGER_MESSAGE_DEPTHBEHAVIORRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behavior_manager
{
template <class ContainerAllocator>
struct DepthBehaviorResult_
{
  typedef DepthBehaviorResult_<ContainerAllocator> Type;

  DepthBehaviorResult_()
    : current_depth(0.0)
    , depth_error(0.0)  {
    }
  DepthBehaviorResult_(const ContainerAllocator& _alloc)
    : current_depth(0.0)
    , depth_error(0.0)  {
  (void)_alloc;
    }



   typedef double _current_depth_type;
  _current_depth_type current_depth;

   typedef double _depth_error_type;
  _depth_error_type depth_error;





  typedef boost::shared_ptr< ::behavior_manager::DepthBehaviorResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behavior_manager::DepthBehaviorResult_<ContainerAllocator> const> ConstPtr;

}; // struct DepthBehaviorResult_

typedef ::behavior_manager::DepthBehaviorResult_<std::allocator<void> > DepthBehaviorResult;

typedef boost::shared_ptr< ::behavior_manager::DepthBehaviorResult > DepthBehaviorResultPtr;
typedef boost::shared_ptr< ::behavior_manager::DepthBehaviorResult const> DepthBehaviorResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behavior_manager::DepthBehaviorResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behavior_manager::DepthBehaviorResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behavior_manager::DepthBehaviorResult_<ContainerAllocator1> & lhs, const ::behavior_manager::DepthBehaviorResult_<ContainerAllocator2> & rhs)
{
  return lhs.current_depth == rhs.current_depth &&
    lhs.depth_error == rhs.depth_error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behavior_manager::DepthBehaviorResult_<ContainerAllocator1> & lhs, const ::behavior_manager::DepthBehaviorResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behavior_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::behavior_manager::DepthBehaviorResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_manager::DepthBehaviorResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_manager::DepthBehaviorResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_manager::DepthBehaviorResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_manager::DepthBehaviorResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_manager::DepthBehaviorResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behavior_manager::DepthBehaviorResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "621fe9e47aa651fd68b5c50b58c4d325";
  }

  static const char* value(const ::behavior_manager::DepthBehaviorResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x621fe9e47aa651fdULL;
  static const uint64_t static_value2 = 0x68b5c50b58c4d325ULL;
};

template<class ContainerAllocator>
struct DataType< ::behavior_manager::DepthBehaviorResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behavior_manager/DepthBehaviorResult";
  }

  static const char* value(const ::behavior_manager::DepthBehaviorResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behavior_manager::DepthBehaviorResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# ======= Feedback =======\n"
"float64 current_depth    # 当前观测深度\n"
"float64 depth_error      # current_depth - target_depth\n"
;
  }

  static const char* value(const ::behavior_manager::DepthBehaviorResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behavior_manager::DepthBehaviorResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_depth);
      stream.next(m.depth_error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DepthBehaviorResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behavior_manager::DepthBehaviorResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behavior_manager::DepthBehaviorResult_<ContainerAllocator>& v)
  {
    s << indent << "current_depth: ";
    Printer<double>::stream(s, indent + "  ", v.current_depth);
    s << indent << "depth_error: ";
    Printer<double>::stream(s, indent + "  ", v.depth_error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOR_MANAGER_MESSAGE_DEPTHBEHAVIORRESULT_H
