// Auto-generated. Do not edit!

// (in-package behavior_manager.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DepthBehaviorResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_depth = null;
      this.depth_error = null;
    }
    else {
      if (initObj.hasOwnProperty('current_depth')) {
        this.current_depth = initObj.current_depth
      }
      else {
        this.current_depth = 0.0;
      }
      if (initObj.hasOwnProperty('depth_error')) {
        this.depth_error = initObj.depth_error
      }
      else {
        this.depth_error = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DepthBehaviorResult
    // Serialize message field [current_depth]
    bufferOffset = _serializer.float64(obj.current_depth, buffer, bufferOffset);
    // Serialize message field [depth_error]
    bufferOffset = _serializer.float64(obj.depth_error, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DepthBehaviorResult
    let len;
    let data = new DepthBehaviorResult(null);
    // Deserialize message field [current_depth]
    data.current_depth = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [depth_error]
    data.depth_error = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 16;
  }

  static datatype() {
    // Returns string type for a message object
    return 'behavior_manager/DepthBehaviorResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '621fe9e47aa651fd68b5c50b58c4d325';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # ======= Feedback =======
    float64 current_depth    # 当前观测深度
    float64 depth_error      # current_depth - target_depth
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DepthBehaviorResult(null);
    if (msg.current_depth !== undefined) {
      resolved.current_depth = msg.current_depth;
    }
    else {
      resolved.current_depth = 0.0
    }

    if (msg.depth_error !== undefined) {
      resolved.depth_error = msg.depth_error;
    }
    else {
      resolved.depth_error = 0.0
    }

    return resolved;
    }
};

module.exports = DepthBehaviorResult;
