// Auto-generated. Do not edit!

// (in-package behavior_manager.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DepthBehaviorGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.target_depth = null;
      this.publish_mismatch = null;
    }
    else {
      if (initObj.hasOwnProperty('target_depth')) {
        this.target_depth = initObj.target_depth
      }
      else {
        this.target_depth = 0.0;
      }
      if (initObj.hasOwnProperty('publish_mismatch')) {
        this.publish_mismatch = initObj.publish_mismatch
      }
      else {
        this.publish_mismatch = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DepthBehaviorGoal
    // Serialize message field [target_depth]
    bufferOffset = _serializer.float64(obj.target_depth, buffer, bufferOffset);
    // Serialize message field [publish_mismatch]
    bufferOffset = _serializer.bool(obj.publish_mismatch, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DepthBehaviorGoal
    let len;
    let data = new DepthBehaviorGoal(null);
    // Deserialize message field [target_depth]
    data.target_depth = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [publish_mismatch]
    data.publish_mismatch = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 9;
  }

  static datatype() {
    // Returns string type for a message object
    return 'behavior_manager/DepthBehaviorGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '0300ee0e4c47883af7d20c2eef863db7';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # ======= Goal =======
    float64 target_depth     # 目标深度（米）
    bool    publish_mismatch # 是否发布深度误差
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DepthBehaviorGoal(null);
    if (msg.target_depth !== undefined) {
      resolved.target_depth = msg.target_depth;
    }
    else {
      resolved.target_depth = 0.0
    }

    if (msg.publish_mismatch !== undefined) {
      resolved.publish_mismatch = msg.publish_mismatch;
    }
    else {
      resolved.publish_mismatch = false
    }

    return resolved;
    }
};

module.exports = DepthBehaviorGoal;
